# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

def pods
    pod 'RealmSwift', '5.2.0'
    pod 'Alamofire'
    pod 'SwiftyJSON', '5.0.0'
    pod 'AlamofireImage', '~> 4.1'
    pod 'MBProgressHUD', '1.2.0'
    pod 'IQKeyboardManagerSwift', '6.5.5'
end

target 'eNews' do
  pods
end
